### ISSUE TITLE
Als beheerder wil ik Excel-bestanden kunnen importeren

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/referentielijsten#13]
### Thema / Theme

Admin

### Omschrijving / Description

Zodat ik niet 1 voor 1 items hoef aan te maken.

**Comment by sytskevanhasselt** [comment]
@bart-maykin  Vraag: hebben jullie heel per ongeluk nog een voorbeeld-Excelbestand, waarmee jullie deze functinaliteit hebben getest?
